################################################################################
# Automatically-generated file. Do not edit!
################################################################################

CPP_UPPER_SRCS := 
ASM_UPPER_SRCS := 
C++M_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
O_SRCS := 
ELF_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
LINKER_SCRIPT := 
SX_SRCS := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
X_SRCS := 
SRC_SRCS := 
X_UPPER_SRCS := 
CCM_UPPER_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
CXXM_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
SMSASM_UPPER_SRCS := 
SMSASM_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C++M_UPPER_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CC_UPPER_DEPS := 
C++M_UPPER_DEPS := 
C++_UPPER_DEPS := 
CPP_UPPER_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
CREF := 
OBJCOPY := 
JMP_UPPER_DEPS := 
ASM_UPPER_DEPS := 
OBJDUMP := 
CXX_DEPS := 
SX_UPPER_DEPS := 
SMSASM_UPPER_DEPS := 
LIBRARY_GENERATOR_OUTPUTTYPE_OUTPUTS := 
SMS_ASM := 
SMSASM_DEPS := 
CXX_UPPER_DEPS := 
JMP_DEPS := 
CCM_DEPS := 
P_UPPER_DEPS := 
CXXM_UPPER_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
CCM_UPPER_DEPS := 
SRC_DEPS := 
CC_DEPS := 
PP_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
ASM_DEPS := 
MAP := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src \
src/smc_gen/Config_PORT \
src/smc_gen/Config_RTC \
src/smc_gen/Config_UART1 \
src/smc_gen/general \
src/smc_gen/r_bsp/board/generic_rl78_g22 \
src/smc_gen/r_bsp/mcu/all \
src/smc_gen/r_bsp/mcu/rl78_g22 \
src/smc_gen/r_pincfg \

