/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : test2_1.cpp
*  Description  : Main Program
*  Creation Date: 2026-03-14
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#ifdef CPPAPP
extern "C" {
#endif
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "r_smc_entry.h"

// #include "Config_UARTA1.h"
#include "Config_UART1.h"
#include "Config_RTC.h"
#include "VFD.h"

#ifdef CPPAPP
}
#endif

// #define _USE_PC_PRINT 0
#undef _USE_PC_PRINT


static uint8_t is_last_SNTP_access_error = 0U;

#define DURATION_SEC_TO_ACCESS_NTP_SERVER (60*60)	// SNTPサーバーにアクセスする間隔（秒）
#define MAX_ALLOWED_SNTP_ERROR_CNT	24UL	// 1日ごとに再起動？

static uint32_t sntp_error_cnt = 0;	// SNTPがエラーになった回数。MAX_ALLOWED_SNTP_ERROR_CNTを超えたら再起動？

static uint16_t sec_cnt = 0;	// 1秒おきに+1する。DURATION_SEC_TO_ACCESS_NTP_SERVERを超えたら、SNTPアクセスし、0クリアされる

#define AT_TIMEOUT_CNT (20*1)	// ATコマンドの応答を待つ秒数。20秒



static uint8_t AT_command_response_buf[UART1_RX_BUF_LEN + 1] = {0};

// PCへの表示。UARTA1が有効である時のみ使う
static void PC_SendLine(uint8_t* const str){
#ifdef _USE_PC_PRINT
	UARTA1SendLine(str);
#endif
}

static void ESP8266_ReceiveResponseAndCheckEquality(uint8_t* const find_str, bool isTransferredToPC){
	const uint8_t len_AT1 = (uint8_t)strlen((char*)find_str);

	while(1){

		if (isUART1ReceivedLine()){
			uint8_t receivedResponse[UART1_RX_BUF_LEN + 1] = {0};

			strcpy((char*)receivedResponse, (char*)UART1_rx_buf);

			// 受信終わったからバッファクリア
			UART1_ClearReceiveBuffer();

			if (isTransferredToPC){
#ifdef _USE_PC_PRINT
				// 受信したらPC側に送信
				const uint8_t len = (uint8_t)strlen((char*)receivedResponse);
				R_Config_UARTA1_Send(receivedResponse, len);
#endif
			}

			// 受信文字列を比較。一致するなら抜ける
			const uint8_t diff_res = (uint8_t)strncmp((char*)receivedResponse, (char*)find_str, len_AT1);

			if (diff_res == 0){
				break;
			}

		}
	}
}

typedef enum {
	AT_OK = 0,
	AT_ERROR
} AT_RESULT;



static AT_RESULT ESP8266_SendAndReceiveATCommand(uint8_t* const AT_comm, bool isTransferredToPC){

	const uint8_t len_AT = (uint8_t)strlen((char*)AT_comm);

	// タイムアウト時間をセット
	timeout_cnt = 0;

	// UART送信バッファの空き待ち
	while (!isUART1SendFinished()){
	}

	// ATコマンド送る
	R_Config_UART1_Send(AT_comm, len_AT);

	// UARTが送信完了するまで待ち
	while (!isUART1SendFinished()){
	}

	// ATコマンドの返信待ち
	while(timeout_cnt < AT_TIMEOUT_CNT){

		if (isUART1ReceivedLine()){

			// 受信文字列を比較。一致するなら抜ける
			uint8_t str_ok[] = "OK";
			const uint8_t* diff_res1 = (uint8_t*)strstr((char*)UART1_rx_buf, (char*)str_ok);

			if (diff_res1 != NULL){
				UART1_ClearReceiveBuffer();
				return AT_OK;
			}

			uint8_t str_error[] = "ERROR";
			const uint8_t* diff_res2 = (uint8_t*)strstr((char*)UART1_rx_buf, (char*)str_error);

			if (diff_res2 != NULL){

				UART1_ClearReceiveBuffer();
				return AT_ERROR;
			}

			// OK, ERROR以外の場合、とりあえずバッファにコピー
			strcpy((char*)AT_command_response_buf, (char*)UART1_rx_buf);

			// コピーしたからUARTA側のバッファはクリア
			UART1_ClearReceiveBuffer();

			if (isTransferredToPC){
#ifdef _USE_PC_PRINT
				// 受信したらPC側に送信
				const uint8_t len = (uint8_t)strlen((char*)AT_command_response_buf);
				R_Config_UARTA1_Send(AT_command_response_buf, len);
#endif
			}
		}
	}


	// timeout
	PC_SendLine((uint8_t*)"timeout\r\n");// debug
	return AT_ERROR;
}

static AT_RESULT AccessSNTPServerAndRefreshRTC(){
	// SNTPサーバーから時間を取得する
	uint8_t AT3[] = "AT+CIPSNTPTIME?\r\n";
	AT_RESULT sntp_res = ESP8266_SendAndReceiveATCommand(AT3, true);

	if (sntp_res == AT_OK){
		sntp_error_cnt = 0;

		// ここでAT_command_response_bufには+CIPSNTPTIME:Wed Apr 29 18:33:31 2026という形の文字列が入っている
		// +13文字目からを、strptime()で読み取る
		// なお、strptime()、20kBくらいメモリを消費する…
		struct tm tes;
		strptime((char*)(AT_command_response_buf + 13), "%a %b %d %H:%M:%S %Y", &tes);

		// 時間が取得できた
		// asctime()で+4kBくらい
		/*
		uint8_t timestr1[50] = {0};
		strcpy((char*)timestr1, asctime(&tes));
		PC_SendLine(timestr1);
		 */

		// RTCにセットする
		R_Config_RTC_Set_CounterValue_TM(tes);
	} else {
		sntp_error_cnt++;
	}

	return sntp_res;
}

static void ESP8266_Init(){
	// ESP8266を初期化していく
    // Resetかける
    PIN_WRITE(ESP8266_nRESET) = 0;

	R_BSP_SoftwareDelay(1000, BSP_DELAY_MILLISECS);

    VFD_Display8Characters((uint8_t*)"WAITCONN");

    // リセット開放。
    PIN_WRITE(ESP8266_nRESET) = 1;

	uint8_t str_AT2[] = "WIFI GOT IP";
	ESP8266_ReceiveResponseAndCheckEquality(str_AT2, true);

	// 定型文
	uint8_t str4[] = "Got \"WIFI GOT IP\" message\r\n";
	PC_SendLine(str4);

	R_BSP_SoftwareDelay(1000, BSP_DELAY_MILLISECS);

    VFD_Display8Characters((uint8_t*)"WAIT AT ");

	// ATコマンドが通じることのテスト
	uint8_t AT0[] = "AT\r\n";
	const AT_RESULT at0_res = ESP8266_SendAndReceiveATCommand(AT0, true);

	if (at0_res != AT_OK){
		PIN_WRITE(LED_ATERROR) = 0;
		HALT();
	}

	R_BSP_SoftwareDelay(2000, BSP_DELAY_MILLISECS);

    VFD_Display8Characters((uint8_t*)"WAITSNTP");

	// SNTP設定する
	uint8_t AT1[] = "AT+CIPSNTPCFG=1,9,\"ntp.nict.jp\",\"jp.pool.ntp.org\",\"time.google.com\"\r\n";
	const AT_RESULT at1_res = ESP8266_SendAndReceiveATCommand(AT1, true);

	if (at1_res != AT_OK){
		PIN_WRITE(LED_ATERROR) = 0;
		HALT();
	}

	R_BSP_SoftwareDelay(5000, BSP_DELAY_MILLISECS);

    VFD_Display8Characters((uint8_t*)"UPDATE..");

	// 一度SNTPサーバーにアクセスしRTC情報を更新
	AT_RESULT sntp_ret = AccessSNTPServerAndRefreshRTC();

	if (sntp_ret != AT_OK){
		PIN_WRITE(LED_ATERROR) = 0;
	}

}


// 1秒おきに処理すべき内容を記載した関数
void ProcessPerOneSecond(){

	if (sntp_error_cnt > MAX_ALLOWED_SNTP_ERROR_CNT) {
		// 再起動？
		ESP8266_Init();
	}

	// エラーLEDの更新（負論理）
	if (is_last_SNTP_access_error == 1U){
		PIN_WRITE(LED_ATERROR) = 0;
	} else {
		PIN_WRITE(LED_ATERROR) = 1;
	}


	// 一定時間おきにSNTPサーバーにアクセスし、時間を補正
	// なお、このカウンターはRTCとは独立に設定する
	if (++sec_cnt == DURATION_SEC_TO_ACCESS_NTP_SERVER) {
		PC_SendLine((uint8_t*)"TRY CONNECT SNTP\r\n");

		const AT_RESULT sntp_ret = AccessSNTPServerAndRefreshRTC();

		if(sntp_ret != AT_OK){
			uint8_t str[] = "AccessSNTPServerAndRefreshRTC() ERROR\r\n";
			PC_SendLine(str);

			is_last_SNTP_access_error = 1U;
		} else {
			is_last_SNTP_access_error = 0U;
		}

		sec_cnt = 0;
	}
}

int main(void)
{

    //---------------------------------------------------------------
	// LED（負論理）
    // PIN_WRITE(LED1) = 1;
    PIN_WRITE(LED_ATERROR) = 1;

    // ESP8266 Res
    PIN_WRITE(ESP8266_nRESET) = 0;

    is_last_SNTP_access_error	= 0U;
    sntp_error_cnt = 0;

    // ESP8266 UART
    // 38400 bps
    R_Config_UART1_Start();
    //    R_Config_UART1_Loopback_Enable(); // 最初に送った文字が連続送信され続けてしまうため、使ってはいけない

    // PC UART
    // 115200 bps
#ifdef _USE_PC_PRINT
    R_Config_UARTA1_Start();
#endif

    // RTC 初期化（24時間モード、1秒ごとの割り込みあり）
    R_Config_RTC_Set_HourSystem(HOUR24);
    R_Config_RTC_Set_ConstPeriodInterruptOn(ONESEC);
    R_Config_RTC_Start();

    // SPI初期化
    //R_Config_CSI20_Start();

    // 全体割り込み許可
    // （これより前は、各種の送受信ができない。送受信完了の処理に割り込みを使っているため）
    EI();

    //---------------------------------------------------------------
    // VFDを初期化する
    VFD_Init();

	// 試しに少し文字表示しておく
    VFD_Display8Characters((uint8_t*)"RL78 CLK");

    //---------------------------------------------------------------
    // PC向け定型文
	uint8_t str[] = "Hello, world from RL78/G23\r\nWait until ESP8266 setup is finished.\r\n";
	PC_SendLine(str);

    //---------------------------------------------------------------
	ESP8266_Init();

	// ループの準備をして
	sec_cnt = 0;

    while(1)
    {
        // TODO: add application code here
    	// 待ち時間は寝ていてもらう
    	HALT();

    	// RTCの1Hz割り込みでHALT状態から復帰。
    	// もし復帰後に、1Hz割り込みのフラグが立っていたら（必ず立っているはず）、1秒おきの処理を実行
    	if (g_rtc_interrupt_flag) {
    		ProcessPerOneSecond();

    		g_rtc_interrupt_flag = false;
    	}
    }
    return 0;
}
